#!/usr/bin/env bash

l() {
	PREFIX="$(date +"%Y-%m-%d %H:%M:%S"): "
	PREFIX_LENGTH=${#PREFIX}

	while IFS= read -r line; do
		echo "${PREFIX}${line}"
		PREFIX="$(printf '%*s' "$PREFIX_LENGTH" " ")"
	done <<<"$1"
}

fetchQuery() {

	QUERY="$1"
	RESULT="$(curl --get -s --data-urlencode "query=$QUERY" 'https://prom.c3re.de/api/v1/query')"
	STATUS="$(echo "$RESULT" | jq -r '.status')"

	if [ "$STATUS" != "success" ]; then
		l "Error: Query failed"
		exit 1
	fi

	echo "$RESULT" | jq -r '.data.result[0].value[1]'
}

send() {
	POWER_PRICE="$(mosquitto_sub -h mqtt.c3re.de -t "c3re/huette/energy/strompreis" -C 1 -W 5)"
	POWER_PRICE="${POWER_PRICE:-0.30}"

	QUERY_TOTAL='(max_over_time(energy{location="Hütte", type="Energymeter", unit="wh"}[1d]) - min_over_time(energy{location="Hütte", type="Energymeter", unit="wh"}[1d])) /1000'
	QUERY_FRIDGE='(max_over_time(energy{location="Hütte", description="Kuehlschrank", unit="Wh"}[1d]) - min_over_time(energy{location="Hütte", description="Kuehlschrank", unit="Wh"}[1d]))/1000'
	QUERY_SERVER='(max_over_time(energy{location="Hütte", description="NOC-Serverschrank", unit="Wh"}[1d]) - min_over_time(energy{location="Hütte", description="NOC-Serverschrank", unit="Wh"}[1d]))/1000'

	VALUE_TOTAL="$(fetchQuery "$QUERY_TOTAL")"
	PRICE_TOTAL=$(echo "$VALUE_TOTAL * $POWER_PRICE" | bc -l)
	PRICE_TOTAL=$(printf "%.2f" "$PRICE_TOTAL")

	VALUE_FRIDGE="$(fetchQuery "$QUERY_FRIDGE")"
	PRICE_FRIDGE=$(echo "$VALUE_FRIDGE * $POWER_PRICE" | bc -l)
	PRICE_FRIDGE=$(printf "%.2f" "$PRICE_FRIDGE")

	VALUE_SERVER="$(fetchQuery "$QUERY_SERVER")"
	PRICE_SERVER=$(echo "$VALUE_SERVER * $POWER_PRICE" | bc -l)
	PRICE_SERVER=$(printf "%.2f" "$PRICE_SERVER")

	VALUE_OTHERS=$(echo "$VALUE_TOTAL - $VALUE_FRIDGE - $VALUE_SERVER" | bc -l)
	PRICE_OTHERS=$(echo "$VALUE_OTHERS * $POWER_PRICE" | bc -l)
	PRICE_OTHERS=$(printf "%.2f" "$PRICE_OTHERS")

	TEXT="Stromverbrauch in der Hütte in den Letzten 24h:
* Gesamt: $VALUE_TOTAL kWh, Kosten: $PRICE_TOTAL €
* Kühlschrank: $VALUE_FRIDGE kWh, Kosten: $PRICE_FRIDGE €
* Serverschrank: $VALUE_SERVER kWh, Kosten: $PRICE_SERVER €
* Sonstiges: $VALUE_OTHERS kWh, Kosten: $PRICE_OTHERS €
Details unter: $DETAILS_LINK"



	l "message: $TEXT"

	while read -r line; do

		COMMAND="$(echo -n "$TEXT" | jq -Rs '{"roomid":"'"$ROOM_ID"'","text":.}')"

		l "$COMMAND"

		echo "$COMMAND" | mosquitto_pub -h mqtt.c3re.de -t "bot/matrix/actions/roommessage" -s -u "$MQTT_USER" -P "$MQTT_PASS"
		sleep 1
	done <<<"$TEXT"

}

till12() {
	CHECKFILE="/data/lastrun"
	if [ ! -f "$CHECKFILE" ]; then
		touch "$CHECKFILE" -d "1970-01-01 00:00:00"
	fi
	NOW="$(date +%s)"
	LASTRUN="$(date -r "$CHECKFILE" +%s)"

	if [ $((NOW - LASTRUN)) -ge 72000 ]; then
		if [ "$(date +%H)" -eq 12 ]; then
			send
			touch "$CHECKFILE"
			l "Sending message, sleeping 20h"
			sleep 20h
		else
			l "it's been a while but it's not noon yet, waiting 1m"
			sleep 1m
		fi
	else
		l "sent recently, waiting 1h"
		sleep 1h
	fi
}

while true; do
	sleep 1m &
	till12
	wait
done
